apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: {{.Values.app_namespace | quote}}
spec:
  type: kv-v2
  mount: {{.Values.vault_kv_mount_path | quote}}
  path: {{.Values.static_app_secret_key | quote}}
  destination:
    name: {{.Values.static_app_secret_name | quote}}
    create: true
  refreshAfter: 5s
  vaultAuthRef: default
  rolloutRestartTargets:
    - kind: Deployment
      name: {{.Values.static_app_name | quote}}
